### ISSUE TITLE
continue to code stub pages for stories (PBL)

### ISSUE THREAD

**Issue by KylieScharf** [KylieScharf/flask_portfolio#52]
Go based off of wireframe
[wireframe](https://docs.google.com/document/d/1FnQvFt1A5EJzbJhW_7VbTkooRa0s77vUuVOOnr6EYmo/edit?usp=sharing)
- [x] area 51 (kylie)
[example page](https://github.com/KylieScharf/flask_portfolio/blob/e488cdc29f0bc5f7e1d22487c903091fea5da224/templates/A51stories/A51story12211.html#L1-L16)
- [x] bermuda triangle (kylie)
[example page](https://github.com/KylieScharf/flask_portfolio/blob/e488cdc29f0bc5f7e1d22487c903091fea5da224/templates/BTstories/BTstory12111.html#L1-L16)
- [x] great pyramid (khushi)
[example page](https://github.com/KylieScharf/flask_portfolio/blob/e488cdc29f0bc5f7e1d22487c903091fea5da224/templates/GPstories/GPstory1122.html#L1-L17)

**Comment by KhushiB24** [comment]
templates/BTstories/BTstory121.html 
templates/GPstories/GPStory12111.html
